apiVersion: v1
kind: Secret
metadata:
  name: rybbit-default-clickhouse-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  clickhouse-password: eW91ci1zdHJvbmctcGFzc3dvcmQ=